export default {
  LADIES_QUOTA: {
    DEFAULT_LIMIT: 0
  },
  SENIOR_CITIZEN_QUOTA: {
    DEFAULT_LIMIT: 0
  },
  GENERAL_QUOTA: {
    DEFAULT_LIMIT: 0
  },
  TATKAL_QUOTA: {
    DEFAULT_LIMIT: 0,
    OPENING_HOURS: "10:00",
    CLOSING_HOURS: "13:00",
    MIN_BOOKING_TIME_HOURS: 1
  },
  PREMIUM_TATKAL_QUOTA: {
    DEFAULT_LIMIT: 0,
    OPENING_HOURS: "10:00",
    CLOSING_HOURS: "17:00",
    MIN_BOOKING_TIME_HOURS: 1
  }
}
